oltp_to_star:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: {{ env_var('DB_USER') }}
      password: {{ env_var('DB_PASSWORD') }}
      dbname: {{ env_var('DB_NAME') }}
      schema: dbt_dev
      threads: 4