oltp_to_star:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: dbt
      password: dbt
      dbname: analytics
      schema: dbt_dev
      threads: 4